export const STANDARD_SKILLS = [
    "Admin",
    "Advocate",
    "Animals",
    "Art",
    "Astrogation",
    "Athletics",
    "Broker",
    "Carouse",
    "Deception",
    "Diplomacy",
    "Drive",
    "Electronics",
    "Engineer",
    "Explosives",
    "Flyer",
    "Gambler",
    "Gunner",
    "Gun Combat",
    "Heavy Weapons",
    "Investigate",
    "Jack of all Trades",
    "Language",
    "Leadership",
    "Mechanic",
    "Medic",
    "Melee",
    "Navigation",
    "Persuade",
    "Pilot",
    "Profession",
    "Recon",
    "Science",
    "Seafarer",
    "Stealth",
    "Steward",
    "Streetwise",
    "Survival",
    "Tactics",
    "Vacc Suit",
];
